### ISSUE TITLE
Issue when start integration

### ISSUE THREAD

**Issue by Developer089** [martinstafford/daikin_d3net#9]
Hello, I can’t start integration because of this Error

Logger: homeassistant.config_entries
Zdroj: config_entries.py:751
První výskyt: 14:19:34 (2 výskyty)
Naposledy logováno: 14:19:55

Error setting up entry Daikin for daikin_d3net
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_d3net/__init__.py", line 47, in async_setup_entry
    await gateway.async_setup()
  File "/config/custom_components/daikin_d3net/d3net/gateway.py", line 88, in async_setup
    system_decoder: SystemStatus = await self._async_read(SystemStatus)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_d3net/d3net/gateway.py", line 127, in _async_read
    response = await self._client.read_input_registers(
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        address=address,
        ^^^^^^^^^^^^^^^^
        count=Decoder.COUNT,
        ^^^^^^^^^^^^^^^^^^^^
        slave=self._slave,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: ModbusClientMixin.read_input_registers() got an unexpected keyword argument 'slave'

**Comment by indranusantara** [comment]
Hi, my integration also broke with the same error after updating HA Core to 2025.9.1. 

I then rolled back the HA Core to 2025.8.3 and the Daikin integration now works fine again.

It seems that something related to modbus was changed in 2025.9.x. Waiting for an update release from Martin.

**Comment by martinstafford** [comment]
Fixed in 1.7.3 with changes from @mohitavva. Please confirm this fixes for you.

**Comment by indranusantara** [comment]
Hi Martin,

Thanks for the update. It is working fine now, with version 1.7.3
